<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => 'd55aa8bb5c95e04fcfb6209c685157a9',
  'MAILER_DSN' => 'gmail://ApprendreSQLMiage@gmail.com:ApprendreSQLMiage33@default?',
  'DATABASE_URL' => 'mysql://w89mqzrcb431vmpe:r12jp4jr6b5e0igy@wb39lt71kvkgdmw0.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/drmnh6tfqulcodjn',
);
